### ISSUE TITLE
Good job！thank you for your great work !however a big bug in this project can you help me ,thankyou

### ISSUE THREAD

**Issue by qingxivar** [dbetm/handwritten-flowchart-with-cnn#29]
Traceback (most recent call last):
  File "C:\Users\Lenovo\.conda\envs\rrett\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "F:/hhx/pythontest/handwritten1013/handler.py", line 461, in <lambda>
    background="green",command = lambda:self.__continue_process(text_nodes,shape_nodes,image_path,window))
  File "F:/hhx/pythontest/handwritten1013/handler.py", line 420, in __continue_process
    flow = graph.generate_graph()
  File "F:\hhx\pythontest\handwritten1013\graph.py", line 227, in generate_graph
    self.nodes = self.__collapse_nodes()
  File "F:\hhx\pythontest\handwritten1013\graph.py", line 91, in __collapse_nodes
    shape_nodes[min_node].set_text(text_nodes[i].get_text())
TypeError: list indices must be integers or slices, not NoneType

this bug how can i deal with this

**Comment by dbetm** [comment]
Answered on #30
