### ISSUE TITLE
Good job! but still have some bug

### ISSUE THREAD

**Issue by qingxivar** [dbetm/handwritten-flowchart-with-cnn#30]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Lenovo\.conda\envs\rrett\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "F:/hhx/pythontest/handwritten1013/handler.py", line 461, in <lambda>
    background="green",command = lambda:self.__continue_process(text_nodes,shape_nodes,image_path,window))
  File "F:/hhx/pythontest/handwritten1013/handler.py", line 427, in __continue_process
    fg.generate_flowchart()
  File "F:\hhx\pythontest\handwritten1013\flowchart_generator\flowchart_generator.py", line 36, in generate_flowchart
    node = self.flow[key]
TypeError: string indices must be integers

are some faults in this bug?

**Comment by dbetm** [comment]
Yeah, sorry for the late reply. I hope still is useful my answer. Basically this happens when the detections are not enough to create the digital version of it. 

What is missing here is handling situations like that, and then display a friendly message saying that the handwritten flowchart couldn't recognized.
